#!/bin/bash

file_name=$1
cv_set=$2
test_set=$3

# aa, ab, ac, ad, ae, (chance a small number of lines get on af)

rm data/cv/$file_name
mv data/part_files/$file_name.$cv_set data/cv/$file_name

rm data/test/$file_name
mv data/part_files/$file_name.$test_set data/test/$file_name

rm data/training/$file_name
cat data/part_files/$file_name.* > data/training/$file_name

cp data/cv/$file_name data/part_files/$file_name.$cv_set
cp data/test/$file_name data/part_files/$file_name.$cv_set
