#!/bin/bash

input_path=$1
file_name=$2

line_count=$(wc -l < $input_path)
part_size=$(printf "%.0f" $(echo ".2*$line_count" | bc ))

if [ -n "$(ls -A data/part_files)" ] ; then
  rm data/part_files/$file_name*
fi

split -l $part_size $input_path $file_name.
mv $file_name.* data/part_files

